version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: petclinic_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - petclinic_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: petclinic_backend
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - petclinic_network
    command: sh -c "sleep 10 && python run.py"

volumes:
  mysql_data:

networks:
  petclinic_network:
    driver: bridge